### PR TITLE
Added version 9 and encryption support

### PR DESCRIPTION
**Pull request by Xenira**
Hello,

I decided to do some work to support v9 PAK files as well as encrypted index and content.

First of all, I am relatively new to rust, so all hints would be appreciated and I can adjust it.
Also sorry for all the formatting changes. I noticed to late, that the auto formatting did a lot of changes. I decided to keep it, as it results in more readable files. I know this makes the diffs harder to read. Apologies for that.

Things done in this PR:
- Added calculation for footer size for various versions (up to 9).
- Added support for encrypted index
- Added support for encrypted files
- Added --encryption-key (-k) command line parameter
- Added version detection based on magic number

Encrypting index and files is not yet supported.
Index and file are Encrypted using aes256.

I was not able to test this on versions other than 9. But Ill do that the next days, to make sure I did not break anything.
I also created test pak files, but could not upload them, as github forks don't support lfs :/

### CODE REVIEW

**Comment by Xenira** [comment]
Hey, sorry for taking so long with this. Had a lot of other stuff going on.

I hope I addressed everything from your comments.
Thanks again for spending time on my commit and helping me improve!

**Comment by panzi** [comment]
(I haven't forgotten about this, just had no time or energy for it so far.)

**Comment by Xenira** [comment]
No problem. Currently doing support for up to version 11 as the game I want to modify has recently updated.
That will be a bigger change though, as it includes secondary indices and stuff.

**Comment by Xenira** [comment]
I finally found some time to get an initial implementation for reading v11 pak files done.
Should I add this to this pr or create a new one? It depends on the changes made here, so I am not sure how we want to handle this.

**Comment by Xenira** [comment]
Closed, as this is superseeded by #11

**Comment by Xenira** [comment]
Closed, as this is superseeded by #11

**Pull request closed without merging**
