### PR TITLE
Add fuse dependency to action

### PR DESCRIPTION
**Pull request by Xenira**
May need to do some further adjustments. Lets see if pipeline works with this change.

### CODE REVIEW

**Review by panzi — APPROVED** [review]

**Comment by panzi** [comment]
All tests fail with `Failed to determine pak file version.`, though. Same locally for me.

**Comment by Xenira** [comment]
Ok, tests fail for some reason....

**Comment by Xenira** [comment]
Hmmm, worked for me. Ill check that.

**Comment by Xenira** [comment]
Ok, works for me. Maybe a problem with git submodule? Can you check if it is checked out at your side?

**Comment by panzi** [comment]
Yes, I've checked them out. `git submodule init; git submodule update`

**Comment by Xenira** [comment]
Hmmm, with my pr #18 the error message changed. Now the sha1 of the files does not match...
The strange thing is, that its working on my machine with a clean workspace.

**Comment by Xenira** [comment]
The strange thing is, that the source digest seems to be wrong. Tested it and got `[116, 111, 81, 22, 64, 
151, 249, 89, 233, 203, 165, 154, 128, 122, 41, 98, 251, 89, 212, 241]` which is the same as the out digest in the test cases

**Comment by panzi** [comment]
Hope I didn't mess anything up with the `.map_or(...)` change? But that is about the SHA1 and it complains that it can't even the version field?

**Comment by Xenira** [comment]
Nah, its not the `.map_or()`. The error in #18 occurs here https://github.com/panzi/rust-u4pak/blob/main/tests/util/mod.rs#L88.
I check if the unpacked files match the original files there.

Your version error seems somehow to be related to the submodule, as #18 resolved that.

**Comment by Xenira** [comment]
Ok, windows f* ed us over. The different hashes are because of line endings. As I needed windows to create the test paks the files inside of the pak files have CRLF line endings.
If compared to the files from the project git the hashes don't match because the files cloned via get have LF endings.

**Comment by Xenira** [comment]
That was it. Build and tests are successful now. Ill redo the pak examples with a new image anyways and change everything to LF with that.

**Comment by panzi** [comment]
Windows git's automatic line ending conversion is evil, IMO. You can deactivate it in some setting.

**Comment by Xenira** [comment]
Yeah. For now I forced crlf in .gitattributes until I recreated the paks

**Comment by panzi** [comment]
Hmm, somehow doesn't work for me locally.

**Comment by Xenira** [comment]
Still the version error?

**Comment by panzi** [comment]
Yes.

**Comment by panzi** [comment]
Even deleted pak-examples and did a new git submodule init/update: no change. Weird.

**Comment by Xenira** [comment]
Can you try switching into the pak-examples directory and pull directly or clone the repo https://github.com/Xenira/ue4-pak-examples.git manually into that folder, just to make sure its really a submodule issue?

**Comment by panzi** [comment]
Tried both, no change. Strange.

**Comment by Xenira** [comment]
Ohhhh, it uses git lfs. Maybe try `git lfs init` and `git lfs pull`

**Comment by panzi** [comment]
`git lfs fetch` and `git lfs checkout` in `pak-examples` did the trick! Now all tests pass!

**Comment by Xenira** [comment]
Nice, I will add a contributing section to the reedme documenting the steps needed.

**Comment by Xenira** [comment]
Ok, I need to find a different solution for hosting the pak examples. My 1gig lfs trafic is gone (180mb in that repo). I booked 50gig for the moment, but will prob change this part soon.

**Comment by panzi** [comment]
I guess if the files really never change they can be directly in the git repo? Or does that also have limitations? Good thing its in an separate test data repo anyway.

**Comment by Xenira** [comment]
Same limitations I guess.

I think the best approach would be to find a file hoster that allows wget and include a script that fetches the files.

**Pull request merged**
