### PR TITLE
Added badges to readme

### PR DESCRIPTION
**Pull request by Xenira**

### CODE REVIEW

**Comment by panzi** [comment]
Btw. I think maybe a change to LGPL or even Mozilla Public License might be a good idea? Because GPL isn't that good for a library. But I don't feel like going all the way to MIT/BSD.

**Comment by Xenira** [comment]
Good idea. I personally like (L)GPL and think its better than MIT/BSD.
As this can now be used as library LGPL would be good.

**Comment by panzi** [comment]
The main difference between LGPL and Mozilla Public License is that MPL allows static linking. And static linking is the default with Rust. But I'm fine with either.

**Comment by Xenira** [comment]
Haven't had a look at Mozilla Public License yet. Let me check it rly quick.

**Comment by Xenira** [comment]
Had a look and MPL looks good :)

**Pull request merged**
